SafeAddString(SI_INVENTORYGRIDVIEW_OFFSETITEMTOOLTIPS_CHECKBOX_LABEL, "アイテムツールチップのオフセット", 1)
SafeAddString(SI_INVENTORYGRIDVIEW_OFFSETITEMTOOLTIPS_CHECKBOX_TOOLTIP, "ツールチップをスクロールリストの左に移動して、アイテムグリッドが隠れないようにします。", 1)

SafeAddString(SI_INVENTORYGRIDVIEW_SKIN_DROPDOWN_LABEL, GetString(SI_COLLECTIBLECATEGORYTYPE11), 1)
SafeAddString(SI_INVENTORYGRIDVIEW_SKIN_DROPDOWN_TOOLTIP, "グリッドビューで使うテクスチャセットを設定します。", 1)

SafeAddString(SI_INVENTORYGRIDVIEW_QUALITYOUTLINES_CHECKBOX_LABEL, "品質枠線の表示", 1)
SafeAddString(SI_INVENTORYGRIDVIEW_QUALITYOUTLINES_CHECKBOX_TOOLTIP, "グリッドアイコンを枠線で目立たせます。", 1)

SafeAddString(SI_INVENTORYGRIDVIEW_MINOUTLINEQUALITY_DROPDOWN_LABEL, "品質枠線を最小限に", 1)
SafeAddString(SI_INVENTORYGRIDVIEW_MINOUTLINEQUALITY_DROPDOWN_TOOLTIP, "設定した品質以上のときのみ品質枠線テクスチャを表示します。", 1)

SafeAddString(SI_INVENTORYGRIDVIEW_GRIDICONSIZE_SLIDER_LABEL, "アイコンのサイズ", 1)
SafeAddString(SI_INVENTORYGRIDVIEW_GRIDICONSIZE_SLIDER_TOOLTIP, "グリッドアイコンの大きさを設定します。アイコン領域は指定したサイズの正方形になります。", 1)

SafeAddString(SI_INVENTORYGRIDVIEW_ICONZOOMLEVEL_SLIDER_LABEL, "アイコンのズームレベル", 1)
SafeAddString(SI_INVENTORYGRIDVIEW_ICONZOOMLEVEL_SLIDER_TOOLTIP, "マウスカーソルを乗せた時のアイコンのズームレベルを設定します。", 1)

SafeAddString(SI_BINDING_NAME_INVENTORYGRIDVIEW_TOGGLE, "グリッド/リスト表示の切り替え", 1)